# .streamlit/secrets.toml

[connections.snowflake]
account = "UHWRIXO.FH48875"
user = "KZE"
password = "mIrak!86@€netFlix"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
